server:
  port: 8010    #port number
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
  
spring:   
  application:
    name: api-gateway  
      
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /actuator
  
logging:
  level:
    com.self.sprintboot.learning.apigateway: DEBUG
