server:
  port: 8098    #service port
 
eureka:         #Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:    
  application:
    name: openmap-weather-service   #service name
     

logging:
  level:
    com.discovery.weather-openmap: DEBUG